import { useEffect, useState, type ReactNode } from "react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { api, errorMessage } from "./services/api";
import type { Analysis, Brief, EvidenceInput, EvidenceRecord, Project } from "./types/api";
import { AnalysisView } from "./components/AnalysisView";
import { BulkEvidence, EvidenceForm } from "./components/EvidenceForm";
import { Card, DetailList, Empty, Notice } from "./components/UI";

const nav = ["Dashboard", "Projects", "Evidence", "Analysis", "Discoveries", "Decision Briefs", "Settings"];
function Layout({ children }: { children: ReactNode }) { return <><header><Link className="brand" to="/">OpenSocial AI <span>exploratory decision support</span></Link><nav aria-label="Primary">{nav.map((item) => <NavLink key={item} to={item === "Dashboard" ? "/" : `/${item.toLowerCase().replaceAll(" ", "-")}`}>{item}</NavLink>)}</nav></header><main><Notice>OpenSocial AI provides exploratory decision support. Human review is required.</Notice>{children}</main></>; }
function useProjects() { const [projects, setProjects] = useState<Project[]>([]); const [error, setError] = useState(""); const refresh = () => { void api.listProjects().then(setProjects).catch((e) => setError(errorMessage(e))); }; useEffect(() => { refresh(); }, []); return { projects, error, refresh, setProjects }; }
function ProjectsPage({ projects, refresh }: { projects: Project[]; refresh: () => void }) { const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [error, setError] = useState(""); const navigate = useNavigate(); async function submit(e: React.FormEvent) { e.preventDefault(); try { const project = await api.createProject(name, description); refresh(); navigate(`/projects/${project.project_id}`); } catch (err) { setError(errorMessage(err)); } } return <><h1>Projects</h1><Card title="Create project"><form className="form" onSubmit={submit}>{error && <Notice kind="error">{error}</Notice>}<label>Project name<input required value={name} onChange={(e) => setName(e.target.value)} /></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label><button>Create project</button></form></Card><Card title="Your projects">{projects.length ? <div className="cards">{projects.map((p) => <Link className="item" key={p.project_id} to={`/projects/${p.project_id}`}><h3>{p.name}</h3><p>{p.description || "No description provided."}</p><small>Created {new Date(p.created_at).toLocaleDateString()}</small></Link>)}</div> : <Empty>Create your first project to begin organising evidence.</Empty>}</Card></>; }
function Dashboard({ projects }: { projects: Project[] }) { return <><h1>Dashboard</h1><div className="metrics"><Card title="Projects"><strong>{projects.length}</strong></Card><Card title="Current project"><strong>{projects.length ? projects[0].name : "None selected"}</strong></Card><Card title="Evidence count"><strong>Open a project</strong><p>Evidence remains scoped to its project.</p></Card><Card title="System status"><strong>Available</strong><p>API-backed exploratory workspace</p></Card></div><Card title="Latest analyses and briefs"><Empty>Open a project to view its evidence, analyses, and decision briefs. No analytics are fabricated.</Empty></Card></>; }
function Workspace() { const { projectId = "" } = useParams(); const [project, setProject] = useState<Project>(); const [evidence, setEvidence] = useState<EvidenceRecord[]>([]); const [analysis, setAnalysis] = useState<Analysis>(); const [brief, setBrief] = useState<Brief>(); const [error, setError] = useState(""); const [problem, setProblem] = useState(""); const [narrative, setNarrative] = useState(false); const [running, setRunning] = useState(false); const [active, setActive] = useState("overview");
  const load = () => { api.getProject(projectId).then(setProject).catch((e) => setError(errorMessage(e))); api.listEvidence(projectId).then(setEvidence).catch((e) => setError(errorMessage(e))); }; useEffect(load, [projectId]);
  async function addEvidence(input: EvidenceInput) { await api.addEvidence(projectId, input); await api.listEvidence(projectId).then(setEvidence); }
  async function bulk(records: EvidenceInput[]) { await api.addBulkEvidence(projectId, records); await api.listEvidence(projectId).then(setEvidence); }
  async function run() { setRunning(true); setError(""); try { setAnalysis(await api.runAnalysis(projectId, problem, narrative)); setActive("analysis"); } catch (e) { setError(errorMessage(e)); } finally { setRunning(false); } }
  async function createBrief() { if (!analysis) return; try { const result = await api.createBrief(projectId, analysis.analysis_id, `${project?.name ?? "Project"} exploratory brief`); setBrief(result.brief); setActive("briefs"); } catch (e) { setError(errorMessage(e)); } }
  if (!project && !error) return <p>Loading project…</p>; if (error && !project) return <Notice kind="error">{error}</Notice>;
  return <><Link to="/projects">← Projects</Link><h1>{project?.name}</h1><p>{project?.description || "No description provided."}</p>{error && <Notice kind="error">{error}</Notice>}<div className="tabs" role="tablist">{[["overview", "Overview"], ["evidence", "Evidence"], ["analysis", "Analysis"], ["discoveries", "Discoveries"], ["briefs", "Briefs"]].map(([key, label]) => <button role="tab" aria-selected={active === key} className={active === key ? "selected" : ""} key={key} onClick={() => setActive(key)}>{label}</button>)}</div>{active === "overview" && <Card title="Workspace overview"><p>{evidence.length} evidence record{evidence.length === 1 ? "" : "s"} currently available for exploratory analysis.</p><p>Human review remains required at every stage.</p></Card>}{active === "evidence" && <><EvidenceForm onSubmit={addEvidence} /><BulkEvidence onSubmit={bulk} /><Card title="Evidence records">{evidence.length ? evidence.map((record) => <details className="record" key={record.evidence_id}><summary>{record.evidence.source_type}: {record.evidence.content.slice(0, 90)}</summary><DetailList value={{ evidence_id: record.evidence_id, ...record.evidence, provenance: record.provenance }} /></details>) : <Empty>Add evidence before running an analysis.</Empty>}</Card></>}{active === "analysis" && <><Card title="Run analysis"><form className="form" onSubmit={(e) => { e.preventDefault(); run(); }}><label>Strategic problem / question<textarea required value={problem} onChange={(e) => setProblem(e.target.value)} placeholder="Why are member organisations struggling to sustain programmes after donor funding ends?" /></label><label className="check"><input type="checkbox" checked={narrative} onChange={(e) => setNarrative(e.target.checked)} /> Include deterministic narrative analysis</label><button disabled={running || !evidence.length}>{running ? "Running exploratory analysis…" : "Run analysis"}</button>{running && <Notice>Analysis is exploratory. It identifies evidence gaps, patterns, and hypotheses; it does not make a decision.</Notice>}</form></Card><AnalysisView analysis={analysis} /></>}{active === "discoveries" && <Discoveries analysis={analysis} />}{active === "briefs" && <Briefs projectId={projectId} analysis={analysis} brief={brief} onGenerate={createBrief} />}</>; }
function Discoveries({ analysis }: { analysis?: Analysis }) { if (!analysis) return <><h2>Discoveries</h2><Empty>Define a strategic question and run an exploratory analysis.</Empty></>; const r = analysis.report; const groups = [["Evidence gaps", "evidence_gap_details"], ["Emerging patterns", "observed_patterns"], ["Conflicting evidence", "evidence_conflicts"], ["Historical connections", "historical_candidates"], ["Cross-sector inspiration", "cross_sector_candidates"], ["Innovation opportunities", "innovation_opportunities"], ["Exploratory hypotheses", "innovation_hypotheses"]] as const; return <><h2>Discoveries</h2><p>Potentially useful learning for human review, not proven recommendations.</p>{groups.filter(([, key]) => r[key]).map(([title, key]) => <Card key={key} title={title}><DetailList value={r[key]} /></Card>)}</>; }
function Briefs({ projectId, analysis, brief, onGenerate }: { projectId: string; analysis?: Analysis; brief?: Brief; onGenerate: () => void }) { const [view, setView] = useState<"details" | "markdown" | "html">("details"); const [content, setContent] = useState(""); async function render(kind: "markdown" | "html") { if (!brief) return; setView(kind); setContent(kind === "markdown" ? await api.getBriefMarkdown(projectId, brief.brief_id) : await api.getBriefHtml(projectId, brief.brief_id)); } return <><h2>Decision Briefs</h2>{!analysis && <Empty>Generate a brief from an analysis for structured human review.</Empty>}{analysis && !brief && <Card title="Generate an exploratory brief"><p>A brief is a structured snapshot for human review. It is not a decision or recommendation.</p><button onClick={onGenerate}>Generate Decision Brief</button></Card>}{brief && <Card title={String(brief.title)}><p>Version {brief.brief_version}. Immutable exploratory snapshot.</p><div className="tabs"><button onClick={() => setView("details")}>Details</button><button onClick={() => render("markdown")}>Markdown</button><button onClick={() => render("html")}>HTML</button></div>{view === "details" ? <DetailList value={brief} /> : view === "markdown" ? <pre>{content}</pre> : <iframe title="Rendered decision brief" sandbox="" srcDoc={content} />}</Card>}</>; }
function StaticPage({ title, children }: { title: string; children: ReactNode }) { return <><h1>{title}</h1><Card>{children}</Card></>; }
export default function App() { const state = useProjects(); return <Layout><Routes><Route path="/" element={<Dashboard projects={state.projects} />} /><Route path="/projects" element={<ProjectsPage projects={state.projects} refresh={state.refresh} />} /><Route path="/projects/:projectId" element={<Workspace />} /><Route path="/evidence" element={<StaticPage title="Evidence">Open a project to add and inspect its evidence.</StaticPage>} /><Route path="/analysis" element={<StaticPage title="Analysis">Open a project to run deterministic exploratory analysis.</StaticPage>} /><Route path="/discoveries" element={<StaticPage title="Discoveries">Discoveries are shown within each project after analysis.</StaticPage>} /><Route path="/decision-briefs" element={<StaticPage title="Decision Briefs">Briefs are generated from a project analysis and remain exploratory snapshots.</StaticPage>} /><Route path="/settings" element={<StaticPage title="Settings">This MVP has no account, governance, or provider configuration controls.</StaticPage>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Layout>; }
