import { useState } from "react";
import type { Analysis } from "../types/api";
import { Card, DetailList, Empty } from "./UI";

type Report = Record<string, unknown>;
type Section = { id: string; title: string; label: string; key: string };
const sections: Section[] = [{ id: "quality", title: "Evidence quality", label: "Evidence quality", key: "evidence_quality" }, { id: "gaps", title: "Evidence gaps", label: "Evidence gap", key: "evidence_gap_details" }, { id: "conflicts", title: "Conflicts", label: "Possible conflict", key: "evidence_conflicts" }, { id: "patterns", title: "Observed patterns", label: "Pattern", key: "observed_patterns" }, { id: "insights", title: "Insights", label: "Insight", key: "insights" }, { id: "opportunities", title: "Innovation opportunities", label: "Exploratory opportunity", key: "innovation_opportunities" }, { id: "hypotheses", title: "Innovation hypotheses", label: "Hypothesis", key: "innovation_hypotheses" }];
const items = (value: unknown): unknown[] => Array.isArray(value) ? value : value === undefined || value === null ? [] : [value];
const asObject = (value: unknown): Report | undefined => value && typeof value === "object" && !Array.isArray(value) ? value as Report : undefined;
const asText = (value: unknown): string | undefined => typeof value === "string" && value.trim() ? value.trim() : typeof value === "number" || typeof value === "boolean" ? String(value) : undefined;
function firstText(record: Report, keys: string[]) { for (const key of keys) { const value = asText(record[key]); if (value) return value; } }
function sourceIds(record: Report) { const value = record.evidence_ids ?? record.source_ids ?? record.evidence_basis ?? record.evidence_id; return items(value).flatMap((item) => typeof item === "string" || typeof item === "number" ? [String(item)] : []); }
function Preview({ text }: { text: string }) { const [open, setOpen] = useState(false); const long = text.length > 280; return <><p className="finding-text">{long && !open ? `${text.slice(0, 280).trimEnd()}…` : text}</p>{long && <button className="text-button" onClick={() => setOpen(!open)}>{open ? "Show less" : "Read more"}</button>}</>; }
function Field({ label, value }: { label: string; value: unknown }) { const text = asText(value); return text ? <p className="finding-field"><strong>{label}</strong>{text}</p> : null; }
export function FindingCard({ value, label }: { value: unknown; label: string }) { const record = asObject(value); if (!record) return <article className="finding-card"><span className="result-label">{label}</span><Preview text={String(value)} /></article>; const title = firstText(record, ["title", "finding", "pattern", "insight", "opportunity", "hypothesis", "description"]); const finding = firstText(record, ["finding", "description", "statement", "pattern", "insight", "opportunity", "hypothesis", "gap", "conflict_description"]); const ids = sourceIds(record); if (!title && !finding && !ids.length) return <article className="finding-card"><span className="result-label">{label}</span><DetailList value={record} /></article>; return <article className="finding-card"><span className="result-label">{label}</span>{title && <h3>{title}</h3>}{finding && finding !== title && <Preview text={finding} />}<Field label="Confidence" value={record.confidence} /><Field label="Uncertainty" value={record.uncertainty} /><Field label="Why it matters" value={record.why_it_matters} /><Field label="Validation question" value={record.validation_question ?? record.investigation_question} /><Field label="Experiment" value={record.experiment ?? record.proposed_experiment} />{ids.length > 0 && <div className="source-chips" aria-label="Source IDs">{ids.map((id) => <span className="source-chip" key={id}>{id}</span>)}</div>}{record.provenance !== undefined && <details className="technical-details"><summary>Provenance and technical detail</summary><DetailList value={{ provenance: record.provenance, evidence_basis: record.evidence_basis, limitations: record.limitations }} /></details>}</article>; }
export function ResultSection({ section, value, initialLimit = Number.POSITIVE_INFINITY }: { section: Section; value: unknown; initialLimit?: number }) { const [expanded, setExpanded] = useState(false); const results = items(value); if (!results.length) return null; const visible = expanded ? results : results.slice(0, initialLimit); return <section id={section.id} className="result-section"><details><summary><span>{section.title}</span><span className="count-badge">{results.length}</span></summary><div className="finding-list">{visible.map((result, index) => <FindingCard key={index} value={result} label={section.label} />)}</div>{results.length > initialLimit && <button className="text-button" onClick={() => setExpanded(!expanded)}>{expanded ? "Show fewer" : `View all ${results.length}`}</button>}</details></section>; }
function Overview({ analysis, report, available }: { analysis: Analysis; report: Report; available: Section[] }) { return <section id="overview"><Card title="Analysis overview"><div className="overview-counts"><div><span>Evidence records</span><strong>{analysis.evidence_ids.length}</strong></div>{available.map((section) => <div key={section.id}><span>{section.title}</span><strong>{items(report[section.key]).length}</strong></div>)}</div><p className="muted">Counts describe the returned exploratory analysis; they are not scores, rankings, or recommendations.</p></Card></section>; }
function QuickFindings({ report }: { report: Report }) { const available = sections.filter((section) => section.id !== "quality" && section.id !== "hypotheses" && items(report[section.key]).length); if (!available.length) return null; return <section id="findings"><Card title="What the analysis found"><div className="quick-findings">{available.map((section) => <div key={section.id}><h3>{section.title}</h3>{items(report[section.key]).slice(0, 3).map((value, index) => <FindingCard key={index} value={value} label={section.label} />)}{items(report[section.key]).length > 3 && <a href={`#${section.id}`}>View all {items(report[section.key]).length}</a>}</div>)}</div></Card></section>; }
function ResultsNav({ available }: { available: Section[] }) { return <nav className="results-nav" aria-label="Analysis results"><a href="#overview">Overview</a>{available.map((section) => <a key={section.id} href={`#${section.id}`}>{section.title.replace("Observed ", "")}</a>)}<a href="#provenance">Provenance</a></nav>; }
function Provenance({ analysis, report }: { analysis: Analysis; report: Report }) { return <section id="provenance" className="result-section"><details><summary><span>Uncertainty and provenance</span><span className="result-label">Uncertainty</span></summary><p>{analysis.responsible_ai}</p><div className="source-chips" aria-label="Analysis evidence IDs">{analysis.evidence_ids.map((id) => <span className="source-chip" key={id}>{id}</span>)}</div>{report.uncertainty !== undefined ? <FindingCard value={{ uncertainty: report.uncertainty, provenance: report.provenance }} label="Uncertainty" /> : null}</details></section>; }
export function AnalysisView({ analysis }: { analysis?: Analysis }) { if (!analysis) return <Empty>Define a strategic question and run an exploratory analysis.</Empty>; const report = analysis.report; const available = sections.filter((section) => items(report[section.key]).length); return <div className="results"><Overview analysis={analysis} report={report} available={available} /><QuickFindings report={report} /><ResultsNav available={available} />{available.map((section) => <ResultSection key={section.id} section={section} value={report[section.key]} />)}<Provenance analysis={analysis} report={report} /></div>; }
export function DiscoveriesView({ analysis }: { analysis?: Analysis }) { if (!analysis) return <><h2>Discoveries</h2><Empty>Define a strategic question and run an exploratory analysis.</Empty></>; const report = analysis.report; const available = sections.filter((section) => section.id !== "quality" && items(report[section.key]).length); return <><h2>Discoveries</h2><p>Potentially useful learning for human review, not proven recommendations.</p>{available.length ? available.map((section) => <ResultSection key={section.id} section={section} value={report[section.key]} initialLimit={3} />) : <Empty>No discoveries are available in this analysis snapshot.</Empty>}</>; }
